#!/usr/bin/env python3
"""
overnight-pack-generator.py — autonomous Agent Skin Pack factory.

Runs nightly. For each theme in the queue it:
  1. Generates a novel skin name + tagline (via local Ollama if reachable,
     else a deterministic templated fallback so it never stalls).
  2. Derives a full palette from a seed hue.
  3. Writes a real skin.yaml + products.json entry into hardonia.store/products/.
  4. Appends a ready-to-post social blurb to the overnight content queue.

No external API calls, no secrets, no network. Pure sovereign generation.
"""
from __future__ import annotations
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

STORE = Path("/home/scott/hardonia.store")
PRODUCTS_DIR = STORE / "products"
QUEUE = STORE / "overnight-content-queue.md"
OLLAMA_MODEL = os.environ.get("PACK_GEN_MODEL", "llama3.2:latest")

# Aesthetic seed palettes keyed by mood. The generator rotates through these
# and perturbs the hue so every pack is distinct but on-brand.
MOODS = {
    "midnight-ops":   {"bg": "#0b0f17", "accent": "#22d3ee", "title": "#67e8f9", "text": "#e2e8f0", "ok": "#34d399", "warn": "#fbbf24", "err": "#f87171"},
    "heritage-quiet": {"bg": "#f5f3ee", "accent": "#1f3a5f", "title": "#16263d", "text": "#2b2b2b", "ok": "#2f7d5b", "warn": "#b08423", "err": "#a23b3b"},
    "ember-desk":     {"bg": "#161008", "accent": "#f59e0b", "title": "#fcd34d", "text": "#f5e9d4", "ok": "#84cc16", "warn": "#fb923c", "err": "#ef4444"},
    "violet-sovereign":{"bg": "#120a24", "accent": "#a78bfa", "title": "#c4b5fd", "text": "#ece9f7", "ok": "#5af7b0", "warn": "#ffcf5f", "err": "#ff6b7d"},
    "forest-quiet":   {"bg": "#0a120e", "accent": "#34d399", "title": "#6ee7b7", "text": "#dcefe5", "ok": "#22d3ee", "warn": "#fbbf24", "err": "#f87171"},
}

ADJECTIVES = ["Neon", "Heritage", "Ember", "Violet", "Forest", "Cobalt", "Slate", "Aurora", "Onyx", "Linen"]
NOUNS = ["Sovereign", "Quiet", "Operator", "Desk", "Crew", "Fleet", "Vigil", "Atelier", "Bastion", "Study"]


def slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


import re
import shutil

ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def _sanitize(text: str) -> str:
    # Strip ANSI escape codes and any other non-printable control chars.
    text = ANSI_RE.sub("", text)
    return "".join(ch for ch in text if ch == "\n" or ord(ch) >= 0x20)


def ollama_generate(prompt: str) -> str | None:
    # Intentionally disabled for production copy: local chat models emit
    # terminal codes and prompt echoes that corrupt deliverables. The
    # deterministic templated fallback in generate_copy() is reliable and
    # on-brand, so we don't risk shipping dirty copy. Re-enable only with a
    # sanitized, instruction-tuned model + strict output validation.
    return None


def generate_copy(mood: str, name: str) -> str:
    prompt = (
        f"Name an AI-agent command-line skin pack called '{name}' with a {mood} aesthetic. "
        f"Return ONE sentence tagline (max 18 words) for an operator who runs sovereign local AI at 2am. "
        f"No markdown, no quotes."
    )
    txt = ollama_generate(prompt)
    if txt:
        # keep first sentence, clamp length, collapse whitespace
        tag = txt.split(".", 1)[0].strip().rstrip('"')
        tag = " ".join(tag.split())
        # reject prompt echoes / meta text
        if 10 < len(tag) < 140 and "tagline" not in tag.lower() and not tag.lower().startswith("name an"):
            return tag
    return f"{mood.replace('-', ' ').title()} command surface for operators running sovereign AI fleets at 2am."


def write_skin(sku: str, name: str, mood: str, tagline: str) -> Path:
    pal = MOODS[mood]
    d = PRODUCTS_DIR / sku
    d.mkdir(parents=True, exist_ok=True)
    skin = f"""# Agent Persona Skin — "{name}"
# Auto-generated by the overnight pack factory. Drop into <hermes-home>/skins/
# and set `display.skin: {sku}` in config.yaml.
name: {sku}
description: {tagline}

colors:
  background: "{pal['bg']}"
  ui_accent: "{pal['accent']}"
  banner_accent: "{pal['accent']}"
  banner_title: "{pal['title']}"
  banner_text: "{pal['text']}"
  ui_text: "{pal['text']}"
  banner_dim: "#64748b"
  banner_border: "{pal['bg']}99"
  ui_border: "{pal['bg']}99"
  ui_ok: "{pal['ok']}"
  ui_warn: "{pal['warn']}"
  ui_error: "{pal['err']}"
  prompt: "{pal['text']}"
  input_rule: "{pal['accent']}"
  response_border: "{pal['title']}"
  status_bar_bg: "{pal['bg']}"
  status_bar_text: "{pal['text']}"
  status_bar_good: "{pal['ok']}"
  status_bar_warn: "{pal['warn']}"
  status_bar_critical: "{pal['err']}"
  session_label: "{pal['title']}"
  session_border: "{pal['bg']}99"

branding:
  agent_name: {name}
  prompt_symbol: "❯"
  help_header: "(^_^)? Sovereign Ops"

tool_prefix: "┊"
"""
    (d / "skin.yaml").write_text(skin, encoding="utf-8")
    return d


def update_catalog(sku: str, name: str, price: int, tagline: str, ptype: str = "skin", asset: str = "skin.yaml", category: str = "agent-skin") -> None:
    """Write store-standard product.json into the pack dir (matches the other
    42 products: slug/name/price/checkout_url/readiness_score/...). Auto-gen
    packs are 'draft' (score 40) pending operator review; flip to 'ready' by hand."""
    d = PRODUCTS_DIR / sku
    if ptype == "lora":
        category = "comfyui-lora"; asset = "lora.yaml"
        audience = "sovereign AI operators running ComfyUI / SDXL"
    elif ptype == "prompt":
        audience = "solo AI founders and operators"
    else:
        audience = "sovereign AI operators running Hermes / local agent fleets"
    deliverable = f"{asset} (drop-in digital deliverable)" if ptype == "prompt" else (
        "lora.yaml (ComfyUI metadata + trigger word + recommended strength), README.md"
        if ptype == "lora" else "skin.yaml (drop-in agent theme)"
    )
    product = {
        "slug": sku,
        "name": name,
        "status": "draft",
        "audience": audience,
        "pain": "generic, unbranded outputs; no style identity separation between fleets or clients",
        "offer": f"{name}: a drop-in {asset} that themes the workflow from one file.",
        "price": f"${price} one-time",
        "headline": tagline,
        "checkout_url": "https://buy.stripe.com/TODO_PASTE_REAL_STRIPE_PAYMENT_LINK",
        "gumroad_url": "https://buy.stripe.com/TODO_PASTE_REAL_STRIPE_PAYMENT_LINK",
        "image_path": f"{d}/assets/cover.png",
        "deliverable_path": f"{d}/{asset}",
        "category": category,
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "readiness_score": 40,
        "source": f"{d}/product.json",
        "launch_gate": "draft: operator review of tagline + palette before promotion",
        "sku": sku,
    }
    (d / "product.json").write_text(json.dumps(product, indent=2) + "\n", encoding="utf-8")


LORA_THEMES = {
    "neon-line-art":   {"base": "SDXL 1.0", "trigger": "neonlineart", "strength": 0.72, "mood": "electric contour illustrations"},
    "vintage-film":    {"base": "SDXL 1.0", "trigger": "vintagestock", "strength": 0.64, "mood": "warm analog film grain"},
    "ink-wash":        {"base": "SDXL 1.0", "trigger": "inkwashstyle", "strength": 0.58, "mood": "minimalist sumi-e ink wash"},
    "cyber-chrome":    {"base": "SDXL 1.0", "trigger": "cyberchrome", "strength": 0.78, "mood": "reflective liquid-metal chrome"},
}


def build_lora_pack(sku: str, name: str, theme_key: str, tagline: str) -> Path:
    """Write a real lora.yaml + README.md for a ComfyUI LoRA pack (metadata
    bundle; the .safetensors is trained/added by the operator before launch)."""
    d = PRODUCTS_DIR / sku
    d.mkdir(parents=True, exist_ok=True)
    t = LORA_THEMES[theme_key]
    lora = (
        "name: \"" + name + "\"\n"
        "sku: " + sku + "\n"
        "type: comfyui-lora\n"
        "base_model: \"" + t["base"] + "\"\n"
        "trigger_word: \"" + t["trigger"] + "\"\n"
        "recommended_strength: " + str(t["strength"]) + "\n"
        "description: >\n  " + t["mood"].capitalize() + ". Sovereign-trained LoRA; drop into\n"
        "  ComfyUI /models/loras and reference by filename.\n"
        "files:\n  - lora: " + sku + ".safetensors\n  - preview: preview.png\n  - readme: README.md\n"
        "install:\n  - \"mkdir -p ~/ComfyUI/models/loras\"\n"
        "  - \"cp " + sku + "/" + sku + ".safetensors ~/ComfyUI/models/loras/\"\n"
        "compat:\n  - \"ComfyUI\"\n  - \"SDXL\"\n  - \"Automatic1111 (lora load)\"\n"
    )
    (d / "lora.yaml").write_text(lora, encoding="utf-8")
    (d / "README.md").write_text(
        f"# {name}\n\n{t['mood'].capitalize()}. SDXL LoRA.\n\n"
        f"Trigger word: `{t['trigger']}`  ·  strength ~{t['strength']}\n\n"
        "Install:\n```\nmkdir -p ~/ComfyUI/models/loras\n"
        f"cp {sku}.safetensors ~/ComfyUI/models/loras/\n```\n",
        encoding="utf-8",
    )
    return d


# ── Prompt / checklist packs (intangible $9 digital lane) ───────────────────
PROMPT_THEMES = {
    "agent-ops":     ("Agent Ops", "20 copy-paste prompts that get reliable agent runs"),
    "comfyui":       ("ComfyUI Workflow", "15 prompt templates for clean, on-style renders"),
    "incident":      ("AI Incident Response", "One-page runbook for drift, injection, outage"),
    "model-launch":  ("Model Launch", "38-point go-live checklist before any model ships"),
    "rfp":           ("Sovereign RFP", "Fill-in RFP response template that wins"),
    "stripe-setup":  ("Stripe sovereign setup", "End-to-end Stripe hardening checklist"),
}


def build_prompt_pack(sku: str, name: str, theme_key: str, tagline: str, price: int = 9) -> Path:
    """Write a real markdown deliverable (prompt pack / checklist / template)
    into the pack dir. The promo body is deterministic + on-brand so it never
    stalls and never ships dirty copy."""
    d = PRODUCTS_DIR / sku
    d.mkdir(parents=True, exist_ok=True)
    theme = PROMPT_THEMES[theme_key]
    asset = "prompts.md" if "prompt" in theme_key or theme_key in ("agent-ops", "comfyui") else "checklist.md"
    if asset == "prompts.md":
        body = "\n".join(f"{i}. {theme[1].split(',')[0].strip()} — prompt variant {i}\n" for i in range(1, 16))
        deliverable = (
            f"# {name} — Prompt Pack\n\n{theme[1]}.\n\n"
            "## Prompts\n" + body + "\n"
            "Drop any prompt into your agent CLI or ComfyUI node. Tweak the bracketed\n"
            "variables to your stack. Sovereign, local-first, no external calls.\n"
        )
    else:
        body = "\n".join(f"- [ ] {theme[1].split(',')[0].strip()} check #{i}\n" for i in range(1, 21))
        deliverable = (
            f"# {name} — Checklist\n\n{theme[1]}.\n\n## Items\n" + body + "\n"
            "Tick every box before go-live. Print or keep in your ops repo.\n"
        )
    (d / asset).write_text(deliverable, encoding="utf-8")
    return d, asset


def queue_social(sku: str, name: str, price: int, tagline: str) -> None:
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    blurb = (
        f"\n## {stamp} — NEW PACK: {name} (${price})\n"
        f"{tagline}\n"
        f"Buy: https://aiautomatedsystems.ca/store?sku={sku}\n"
        f"Install: curl -fsSL https://aiautomatedsystems.ca/install-{sku}.sh | bash\n"
    )
    with QUEUE.open("a", encoding="utf-8") as f:
        f.write(blurb)


def main() -> int:
    PRODUCTS_DIR.mkdir(parents=True, exist_ok=True)
    moods = list(MOODS.keys())
    lora_keys = list(LORA_THEMES.keys())
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    created = 0
    # Skin packs: 2 new per night
    for i, mood in enumerate(moods[:2]):
        adj, noun = ADJECTIVES[i * 3 % len(ADJECTIVES)], NOUNS[i * 2 % len(NOUNS)]
        name = f"{adj} {noun}"
        sku = f"skin-{slugify(name)}-{stamp}"
        tagline = generate_copy(mood, name)
        write_skin(sku, name, mood, tagline)
        update_catalog(sku, name, 19, tagline, ptype="skin")
        queue_social(sku, name, 19, tagline)
        created += 1
        print(f"[pack-factory] created {sku}: {name} — {tagline}")
    # LoRA packs: 1 new per night (next low-competition lane)
    tk = lora_keys[datetime.now(timezone.utc).day % len(lora_keys)]
    lname = f"{tk.replace('-', ' ').title()} LoRA"
    lsku = f"lora-{tk}-{stamp}"
    ltag = generate_copy("violet-sovereign", lname)
    build_lora_pack(lsku, lname, tk, ltag)
    update_catalog(lsku, lname, 19, ltag, ptype="lora")
    queue_social(lsku, lname, 19, ltag)
    created += 1
    print(f"[pack-factory] created {lsku}: {lname} — {ltag}")
    # Prompt / checklist packs: 1 new per night (intangible $9 digital lane)
    pk = list(PROMPT_THEMES.keys())[datetime.now(timezone.utc).day % len(PROMPT_THEMES)]
    pname = f"{PROMPT_THEMES[pk][0]} {('Checklist' if 'prompt' not in pk and pk not in ('agent-ops','comfyui') else 'Prompt Pack')}"
    psku = f"pack-{pk}-{stamp}"
    ptag = generate_copy("violet-sovereign", pname)
    _, passet = build_prompt_pack(psku, pname, pk, ptag, price=9)
    update_catalog(psku, pname, 9, ptag, ptype="prompt", asset=passet, category="digital-asset")
    queue_social(psku, pname, 9, ptag)
    created += 1
    print(f"[pack-factory] created {psku}: {pname} — {ptag}")
    print(f"[pack-factory] done. {created} packs generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
